name: house_price_project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pyopenssl=24.2.1
  - cryptography=43.0.3
  - typer
  - loguru
  - tqdm
  - ruff
  - pytest
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scikit-learn
  - tensorflow
  - tensorboard
  - mlflow
  - dvc
  - pip:
      - python-dotenv
      - mkdocs
      - -e .